### ISSUE TITLE
Wrong typings for .customHostnames.fallbackOrigin.get

### ISSUE THREAD

**Issue by visortelle** [cloudflare/cloudflare-typescript#1123] opened 2024-07-05 12:26 UTC
The incorrect type is `unknown | string | null`.

The actual API response has the following form:

```json
{
   "origin":"abc.example.com",
   "status":"active",
   "created_at":"2024-05-31T16:42:26.562994Z",
   "updated_at":"2024-06-24T11:22:27.907453Z"
}
```

See also this issue: https://github.com/cloudflare/cloudflare-typescript/issues/1122
Probably many of the API responses have the wrong type.

**Comment by jacobbednarz** [comment] 2024-07-05 17:05
duplicate of #1112

**Closed** 2024-07-05 17:05 UTC
